ContosoUniversity/Controllers/RoleAdminController.cs
using ContosoUniversity.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace ContosoUniversity.Controllers
{

    public class RoleAdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        public RoleAdminController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result
                    = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }
            return View("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<IdentityUser> members = [];
            List<IdentityUser> nonMembers = [];

            foreach (IdentityUser user in _userManager.Users)
            {
                List<IdentityUser> list = await _userManager.IsInRoleAsync(user, role.Name)
                                ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleModificationModel Model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                //The ?? operator is a null-coalescing operator, which means that
                //if model.IdsToAdd is null, then it will be replaced by an empty
                //string array using System.Array.Empty<string>().
                //So, this loop will iterate over the model.IdsToAdd array if it
                //is not null, or an empty array if it is null.
                foreach (string userId in Model.IdsToAdd ?? System.Array.Empty<string>())
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, Model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
                foreach (string userId in Model.IdsToDelete ?? System.Array.Empty<string>())
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, Model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                return await Edit(Model.RoleId);
            }
        }
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        } 

    }
}

ContosoUniversity/Controllers/StudentsController.cs
using ContosoUniversity.Data;
using ContosoUniversity.Data.DataAccess;
using ContosoUniversity.Models;
using ContosoUniversity.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;

namespace ContosoUniversity.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IRepositoryWrapper _repo;

        public StudentsController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        [TempData] /*Assigned value will only be available until next request */
        public string Message { get; set; }
        public int iPageSize = 5;

        public IActionResult Index(string sortBy = "LastName", string searchString = "", 
            int page = 1)
        {
            IEnumerable<Student> students;
            Expression<Func<Student, Object>> orderBy;
            string orderByDirection;
            int iTotalStudents;

            ViewData["NameSortParam"] = sortBy == "LastName" ? "LastName_desc" : "LastName";
            ViewData["DateSortParam"] = sortBy == "EnrollmentDate" ? "EnrollmentDate_desc" : "EnrollmentDate";
            ViewData["CurrentFilter"] = searchString;
            ViewData["Message"] = Message;

            if (string.IsNullOrEmpty(sortBy))
            {
                sortBy = "LastName";
            }

            if (sortBy.EndsWith("_desc"))
            {
                sortBy = sortBy.Substring(0, sortBy.Length - 5);
                orderByDirection = "desc";
            }
            else
            {
                orderByDirection = "asc";
            }

            orderBy = p => EF.Property<object>(p, sortBy);  //e.g. p => p.LastName

            if (searchString == "")
            {
                iTotalStudents = _repo.Student.FindAll().Count();
                students = _repo.Student.GetWithOptions(new QueryOptions<Student>
                {
                    OrderBy = orderBy,
                    OrderByDirection = orderByDirection,
                    Where = s => s.LastName.Contains(searchString) || s.FirstName.Contains(searchString),
                    PageNumber = page,
                    PageSize = iPageSize

                });
            }
            else
            {
                iTotalStudents = _repo.Student.FindByCondition(s => s.LastName.Contains(searchString) || s.FirstName.Contains(searchString)).Count();
                students = _repo.Student.GetWithOptions(new QueryOptions<Student>
                {
                    OrderBy = orderBy,
                    OrderByDirection = orderByDirection,
                    Where = s => s.LastName.Contains(searchString) || s.FirstName.Contains(searchString),
                    PageNumber = page,
                    PageSize = iPageSize
                });
            }


            return View(new StudentListViewModel
            {
                Students = students,
                PagingInfo = new PagingInfoViewModel
                {
                    CurrentPage = page,
                    ItemsPerPage = iPageSize,
                    TotalItems = iTotalStudents
                }
            });
        }

        public IActionResult Details(int id)
        {
            var student = _repo.Student.GetStudentWithEnrollmentDetails(id);
            if (student == null)
                return NotFound();
            else
            {
                return View(student);
            }
        }

        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("Edit", new Student());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            return View(_repo.Student.GetById(id));
        }

        [HttpPost]
        public IActionResult Edit(Student student)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (student.StudentID == 0)
                    {
                        student.EnrollmentDate = DateTime.Now;
                        _repo.Student.Create(student);
                        Message = $"Student {student.LastName} added succesfully.";
                    }
                    else
                    {
                        _repo.Student.Update(student);
                        Message = $"Student {student.LastName} updated succesfully.";
                    }

                    _repo.Save();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }
            ViewBag.Action = (student.StudentID == 0) ? "Add" : "Edit";
            return View(student);
        }

        public IActionResult Delete(int id)
        {
            var student = _repo.Student.GetById(id);
            if (student == null)
                return NotFound();
            else
            {
                return View(student);
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteStudent(Student student)
        {
            if (student != null)
            {
                _repo.Student.Delete(student);
                _repo.Save();
                Message = $"Student {student.LastName} deleted succesfully.";

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ErrorMessage = "Unable to Delete student";
                return View(student);
            }
        }
    }
}

ContosoUniversity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!-- CSIS3734 (2024): Unit 4 (Contoso University) -->
<!-- Add Personal details here-->
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--  Bootstrap -->
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/css/bootstrap.min.css" />
    <!-- Font Awesome -->
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/all.min.css" />

    <title>Contoso - @ViewData["Title"]</title>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <div class="container">
            <!-- Brand -->
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">CONTOSO</a>

            <!-- Toggler/collapsible Button -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#MyNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse"
                 id="MyNavbar">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="About">About</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="Students" asp-action="Index">Students</a></li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Admin</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Admin"
                                        asp-action="Index">User Management</a>
                                    <a class="dropdown-item" asp-controller="RoleAdmin"
                                       asp-action="Index">Role Management</a>
                                </div>
                            </li>
                        }
                    }
                </ul>

                <ul class="navbar-nav navbar-right">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-link">Hello, @User.Identity.Name</li>
                        <li class="nav-item">
                            <form asp-controller="Account" asp-action="Logout" method="post">
                                <button class="btn btn-link nav-link" type="submit">Log Out</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Log in</a>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="pb-3">
            @RenderBody()
        </div>
    </div>

    <div class="container">
        <div class="border-top footer text-muted text-center small">
            <p>Created by: Initials.Surname (Student number)<br />
            <span class="fas fa-copyright"></span> CSIS3734 - UFS @DateTime.Now.Year</p>
        </div>
    </div>

    <!-- JavaScript -->
    <script asp-src-include="lib/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

ContosoUniversity/Views/Shared/_StudentDetails.cshtml
@model Student

<p>
    <span class="fw-bold">
        @Html.DisplayNameFor(model => model.LastName)
    </span><br />
    @Model.LastName
</p>
<p>
    <span class="fw-bold">
        @Html.DisplayNameFor(model => model.FirstName)
    </span><br />
    @Model.FirstName
</p>
<p>
    <span class="fw-bold">
        @Html.DisplayNameFor(model => model.Initials)
    </span><br />
    @Model.Initials
</p>
<p>
    <span class="fw-bold">
        @Html.DisplayNameFor(model => model.EnrollmentDate)
    </span><br />
    @Model.EnrollmentDate.ToShortDateString()
</p>